# Sequences from RCSB FASTA files supplied by the author (chain used noted)
RIBOZYMES = {
 "Pistol (5K7C, chain A, 47 nt)": "CGUGGUUAGGGCCACGUUAAAUAGUUGCUUAAGCCCUAAGCGUUGAU",
 "Twister-sister (5Y85, chain B, 50 nt)": "GCCGCCGCUGGUGCAAGUCCAGCCACGCUUCGGCGUGGGCGCUCAUGGGU",
 "Hammerhead (1HMH, RNA strand, 34 nt)": "GGCGACCCUGAUGAGGCCGAAAGGCCGAAACCGU",
 "Varkud satellite (9A0V, 101 nt)": "GCAGGGAACUCACCUCCCCUUGGGUCGUAGCAGUUGACUACUGUUAUGUGAUUGGUAGAGGCUAAGUGACGCCGUAAGGCGCAGCACAGCACAAGCCCGCG",
 "Lariat-capping (6G7Z, chain A, 132 nt)": "CAUCCGGUAUCCCAAGACAUCUUCGGGUGGGUUGGGAAGUAUCAUGGCUAAUCACCAUGAUGCAAUCGGGUUGAACACUUAAUUGGGUUAAAACGGUGGGGGACGAUCCCGUAACAUCCGUCCUAACGGCGA",
}
